# Generated by Django 3.2.2 on 2021-05-14 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_listings_listing'),
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Realtors',
            new_name='Realtor',
        ),
    ]
